name: Unzip Bot Files
on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract ZIP File
        run: |
          if [ -f "BELAL-BOTX666-MAX-main.zip" ]; then
            unzip -o BELAL-BOTX666-MAX-main.zip
          elif [ -f ".github/BELAL-BOTX666-MAX-main.zip" ]; then
            unzip -o .github/BELAL-BOTX666-MAX-main.zip
          else
            echo "Zip file not found!" && exit 1
          fi

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Unzipped bot files successfully"
          git push
          
